### ISSUE TITLE
Webhook to API

### ISSUE THREAD

**Issue by bjendres** [systopia/CiviProxy#32]
Similar to #18 and #26, we want to proxy to be able to receive webhooks/callbacks and forward the configuration to the target system's API.

For that, this hook needs the following features:
* multiple configurations, one default
* IP/Range filter
* parameter sources (POST/json, ...)
* parameter sanitation
* response processing (mapping of API response to HTTP status codes)

**Comment by pbatroff** [comment]
This is implemented  and works well with correct configuration setup. 

In [here](https://github.com/systopia/CiviProxy/blob/master/proxy/webhook2api.php#L114) and [here](https://github.com/systopia/CiviProxy/blob/master/proxy/webhook2api.php#L128) return values from the internal CiviAPI is exposed. 

I would propose to return 200 here and log the error internally to civiproxy_log, since the webhook got parsed and forwarded to the API correctly.

@bjendres do you have an opinion here?

**Comment by pbatroff** [comment]
I think we can close here
